version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.frontend
    ports:
      - '5173:5173'

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
