# Use a base image with Node.js pre-installed
FROM node:16.17.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port on which the server will run
EXPOSE 3000

# Command to run the server
CMD ["npm", "dev"]
